AWSTemplateFormatVersion: 2010-09-09
Description: Deploys a CodeCommit repository
Parameters:
  RepositoryName:
    Type: String
    Description: The name of the CodeCommit repository created by this template
  RepositoryDescription:
    Type: String
    Description: The description of the repository
    Default: ""
  CodeBucket:
    Type: String
    Description: The URI of the S3 bucket that contains the demo code that will be uploaded to CodeCommit by this template
    Default: ""
  CodeZipFile:
    Type: String
    Description: The name of the zip file containing the demo code
    Default: ""
  TriggerTopicARN:
    Type: String
    Description: The ARN of the SNS Topic to which the triggers will send messages
    Default: ""
Resources: 
  Repository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      RepositoryDescription: !Ref RepositoryDescription
      Triggers:
        - !If
          - UseTrigger
          - Branches: []
            DestinationArn: !Ref TriggerTopicARN
            Events:
              - all
            Name: PRTrigger
          - !Ref 'AWS::NoValue'
      Code: 
        !If
          - UploadCode
          - S3:
              Bucket: !Ref CodeBucket
              Key: !Ref CodeZipFile
          - !Ref 'AWS::NoValue'
      Tags:
        - Key: name
          Value: !Ref RepositoryName
        - Key: class
          Value: DOP-C01
        - Key: section
          Value: 4
Conditions:
  UploadCode: !Not [!Or [!Equals [!Ref CodeBucket, ""], !Equals [!Ref CodeZipFile, ""]]]
  UseTrigger: !Not [!Equals [!Ref TriggerTopicARN, ""]]
Outputs:
  Repository:
    Description: The ID of the CodeCommit repository created by this template
    Value: !Ref Repository
    Export:
      Name: CodeCommitRepository
